/**
 * The character budget must bound what the model actually receives.
 *
 * It did not. The cost function charged an item at `body + title + citation`,
 * while `renderPacket` emitted a header, a ~250-character advisory, five labelled
 * lines per item, a fenced citation, markdown scaffolding and a closing note —
 * none of it counted. So a packet declaring a 4,000-character ceiling routinely
 * delivered several hundred more, and the overrun grew with every item.
 *
 * The fix is structural rather than arithmetic: one `renderItem`, called by both
 * the budget and the renderer, so the two cannot drift again.
 */

import { test } from "node:test";
import assert from "node:assert/strict";
import { assemblePacket, overheadFor, renderPacket } from "../src/core/packet.ts";
import type { CitedItem } from "../src/core/types.ts";

const NOW = new Date("2026-08-31T00:00:00.000Z");

/** Deliberately verbose in every field the old cost function ignored. */
function fatItem(id: string, component: string): CitedItem {
  return {
    id,
    sourceKind: "lesson",
    title: `a lesson with a reasonably long title, number ${id}`,
    body: "b".repeat(400),
    citation: `lesson:${id}:with-a-long-citation-reference`,
    scope: ["build", "generate", "react", "typescript", "vite"],
    limits: [
      "Observed on Vite + React + TypeScript projects generated by this builder. Not verified anywhere else.",
      "A second limit, because a lesson may carry several and every one of them is rendered.",
    ],
    occurredAt: "2026-08-30T00:00:00.000Z",
    ageDays: 1,
    domain: "build",
    component,
    score: 1,
    reason: "matched trigger tag `type-error` from this build's own failure",
  };
}

test("the counted budget matches what render emits", () => {
  const candidates = Array.from({ length: 12 }, (_, i) => fatItem(`i${i}`, `component-${i}`));
  const maxChars = 3_000;

  const packet = assemblePacket(candidates, {
    scope: { projectId: "p" },
    task: "a task with enough words in it to matter to the header's own cost",
    now: NOW,
    maxChars,
  });

  const rendered = renderPacket(packet);
  assert.ok(packet.items.length > 1, "the case is only interesting with several items");

  // The whole claim, in one line. Before the fix this exceeded the ceiling by
  // the header plus roughly 150 characters per item.
  assert.ok(
    rendered.length <= maxChars,
    `rendered ${rendered.length} characters against a stated ceiling of ${maxChars}`,
  );
});

test("the first item is delivered even when it alone exceeds the ceiling", () => {
  // Long-standing behaviour, kept deliberately: an empty packet helps nobody, so
  // one item always survives. It is stated here so the budget change above cannot
  // be read as having introduced it.
  const packet = assemblePacket([fatItem("only", "c")], {
    scope: { projectId: "p" },
    task: "t",
    now: NOW,
    maxChars: 10,
  });
  assert.equal(packet.items.length, 1);
  assert.equal(packet.omissions.droppedForBudget, 0);
});

test("the overhead charged covers the advisory, which was the largest uncounted piece", () => {
  // The header is emitted on every packet and was never counted at all. The
  // advisory inside it is ~250 characters on its own — more than a short lesson
  // body — so a reserve that did not cover it would leave the ceiling meaning
  // roughly what it meant before.
  const scope = { workspace: "default", projectId: "p" } as const;
  const packet = assemblePacket([], { scope: { projectId: "p" }, task: "a task", now: NOW });
  const reserved = overheadFor(scope, "a task", packet.advisory);

  assert.ok(packet.advisory.length > 100, "the advisory is substantial, which is the point");
  assert.ok(reserved > packet.advisory.length, "the reserve must at least cover the advisory");
  assert.ok(reserved > overheadFor(scope, "a task", ""), "and it must grow with the advisory");

  // Reserved at the widest plausible count width rather than at zero: reserving
  // too little is how a ceiling silently stops being one.
  assert.ok(
    overheadFor(scope, "a task", packet.advisory) >= overheadFor(scope, "a", packet.advisory),
    "a longer task costs at least as much as a shorter one",
  );
});

test("an empty packet still says why it is empty", () => {
  const packet = assemblePacket([], { scope: { projectId: "p" }, task: "t", now: NOW });
  const rendered = renderPacket(packet);
  assert.match(rendered, /No applicable prior observations/);
  assert.ok(packet.omissions.note.length > 0, "a zero must never be silent");
});
